### ISSUE TITLE
Validator error

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#277] opened 2018-08-22 18:05 UTC
In the last \answer of 

https://ximera.osu.edu/mooculus/understandingFunctions/exercises/06_02_ex_16-29

![image](https://user-images.githubusercontent.com/1376703/44481641-5b880e00-a614-11e8-8c06-1594d61cbe05.png)

but...

![image](https://user-images.githubusercontent.com/1376703/44481673-7064a180-a614-11e8-99cc-b0bd07546c89.png)

**Comment by bartsnapp** [comment] 2018-08-22 18:30
It looks like it doen't know what sqrt(e) is...

**Comment by kisonecat** [comment] 2018-08-22 18:48
I can reproduce this error with math-expressions, so this should be fixable
soon.

**Comment by kirollosmasood** [comment] 2018-08-23 00:03
There are so many open issues with all the repos in XimeraProject and Mooculus. Are all of these actually still open or have some of them been resolved without pushing the button..?

**Comment by kirollosmasood** [comment] 2018-08-23 00:25
Ah. On a more relevant note, the same issue appears in the fifth answer box here: https://ximera.osu.edu/mooculus/review/refreshPrerequisites/exerciseList/review/refreshPrerequisites/definiteIntegrals

I can go and change \sqrt{e} to e^{1/2} as a temporary fix, but I don't know if this is necessary since a fix to the validator might be coming soon, aside from the fact that students might lose their work this way.

**Comment by kisonecat** [comment] 2018-08-23 00:34
This bug is fixed in https://github.com/kisonecat/math-expressions/commit/f57c75528981a2416a7570e2e1d1c2ef44b28f40 but I haven't yet deployed the new server at ximera.osu.edu

**Closed by kisonecat** 2018-08-23 00:34 UTC
