### ISSUE TITLE
/mooculus/normalVectors/exercisesParametricPlots/exerciseList/normalVectors/exercisesParametricPlots/record

### ISSUE THREAD

**Issue by bartsnapp** [XimeraProject/server#202] opened 2018-02-02 17:54 UTC
Hey I want to be able to see my answer after I type it in....

Currently sometimes the answer is too long. And the answer box is too small.

boooo.

**Comment by kisonecat** [comment] 2018-02-02 18:46
I agree!

This is a duplicate of https://github.com/XimeraProject/server/issues/200

**Closed by kisonecat** 2018-02-02 18:46 UTC
