### ISSUE TITLE
/course/mooculus/calculus1/master/samplePractice/samplePractice2

### ISSUE THREAD

**Issue by Brunonj** [XimeraProject/server#126] opened 2016-09-06 03:27 UTC
For some of the intervals it will accept -\infnty but not -infinity and similiarly for infinity

**Comment by bartsnapp** [comment] 2016-09-06 13:05
hmm

\infinity should never work. Also I cannot reproduce the error. 

see screen shot.
![infty](https://cloud.githubusercontent.com/assets/1376703/18274548/eb3cce9c-7410-11e6-965a-58158430ba53.png)

on the other hand, I noticed that the brackets are wrong with the remaining problem sqrt(5-x^2) etc.

Fixed now, though you will need to update.

**Closed by bartsnapp** 2016-09-06 13:05 UTC
